# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='activation',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='backupdir',
            field=models.FilePathField(allow_files=False, allow_folders=True, default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='command',
            field=models.CharField(default='get', max_length=10),
        ),
        migrations.AddField(
            model_name='connection',
            name='deleteflag',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='excluderegex',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='connection',
            name='host',
            field=models.CharField(default='localhost', max_length=30),
        ),
        migrations.AddField(
            model_name='connection',
            name='includeregex',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AddField(
            model_name='connection',
            name='localdir',
            field=models.FilePathField(allow_files=False, allow_folders=True, default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='logfile',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='password',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='connection',
            name='private_key',
            field=models.FilePathField(default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='protocol',
            field=models.CharField(default='sftp', max_length=10),
        ),
        migrations.AddField(
            model_name='connection',
            name='remotedir',
            field=models.FilePathField(allow_files=False, allow_folders=True, default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='statuslogdir',
            field=models.FilePathField(allow_files=False, allow_folders=True, default=''),
        ),
        migrations.AddField(
            model_name='connection',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='connection',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
