# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0002_auto_20160925_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='excluderegex',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='connection',
            name='includeregex',
            field=models.CharField(default='', max_length=10),
        ),
    ]
