# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0003_auto_20160925_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='logfile',
            field=models.FilePathField(blank=True, default=''),
        ),
    ]
