# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0004_auto_20160925_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='excluderegex',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='connection',
            name='includeregex',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
